TC-737 - office locater searchbar updates
USSBA/sba-gov-katana pull request #1164
Opened 2021-02-24 20:45 UTC by peggles2

This pull request updates the local assistance search bar with the following changes. 

- Update from “Near” to “Business Zip Code”. and  Remove nested help text inside the field.
- Update the validation to only fire when focus is removed from the field or the Search button is clicked.
- Do not execute the search if the zip code validation is failing.
- Remove “Find Field”
- Update Find a Lender search to also have the same validation setup

![Screen Shot 2021-02-24 at 3 41 46 PM](https://user-images.githubusercontent.com/7727136/109063222-ebf8ab00-76b6-11eb-950f-d23e15dfd797.png)

2021-02-25 15:25 UTC, kscoulter requested changes
Very clean code. Add some tests and refactor a bit for clarity and it should be good to merge :)

2021-02-25 15:25 UTC, kscoulter commented on src/client/components/organisms/primary-search-bar/primary-search-bar.jsx
> +    if (this.props.onSearch && this.props.isValid !== false) {
this can be shortened to `if (this.props.onSearch && this.props.isValid)`

2021-02-25 15:25 UTC, kscoulter commented on src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
> +      isValid: true
can we rename this to something more descriptive, like `isValidSearchTerm` or `isValidZipcode` or `allowSearch`

2021-02-25 15:25 UTC, kscoulter commented on src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
> +                  this.setState({ isValid: isValid })
because the state variable and the local variable are called the same thing, this can be shortened to `this.setState({ isValid })`

2021-02-25 22:44 UTC, peggles2 commented on src/client/components/organisms/primary-search-bar/primary-search-bar.jsx
> +    if (this.props.onSearch && this.props.isValid !== false) {
it has to check just for false. because other apps are using this component and isValid will be undefined and it should be able to go through this condition.

2021-02-25 22:47 UTC, peggles2 commented on src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
> +      isValid: true
I think its clear when each component is using it?  its used in TextInput so you know that your checking for a valid TextInput. I am keeping with what it was named before.

2021-02-25 22:48 UTC, peggles2 commented on src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
> +                  this.setState({ isValid: isValid })
good idea

2021-02-26 14:59 UTC, kscoulter commented on src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
> +      isValid: true
But you're using it in the lender page component state. That implies that the whole lender page status can be valid or invalid.

2021-02-26 15:40 UTC, kscoulter requested changes

2021-02-26 15:40 UTC, kscoulter commented on package.json
> +    "@testing-library/user-event": "^12.7.3",
does it have to be here instead of dev dependencies?

2021-02-26 15:40 UTC, kscoulter commented on test/jest/client/components/pages/office-lookup-page/office-lookup-page.test.js
> +import 'react-testing-library/cleanup-after-each'
what does this do?

2021-02-26 15:42 UTC, peggles2 commented on test/jest/client/components/pages/office-lookup-page/office-lookup-page.test.js
> +import 'react-testing-library/cleanup-after-each'
it was in the other react testing library so I applied it here.

2021-02-26 16:13 UTC, peggles2 commented on test/jest/client/components/pages/office-lookup-page/office-lookup-page.test.js
> +import 'react-testing-library/cleanup-after-each'
looks like it cleans up after each test.

2021-02-26 17:41 UTC, kscoulter approved these changes
LGTM

2021-02-26 20:51 UTC, kscoulter approved these changes
Approved, but with one minor change requested

2021-02-26 20:51 UTC, kscoulter commented on test/jest/client/components/pages/office-lookup-page/office-lookup-page.test.js
> -  test('zip code value can be empty when you click search', () => {
Could you do a test where the user doesn't type anything in the field instead of typing `''`? Seems more likely

2021-03-02 16:42 UTC, kscoulter requested changes
Just one small change requested. Let's make sure search bar functionality is not altered for other pages.

2021-03-02 16:42 UTC, kscoulter commented on src/client/components/organisms/primary-search-bar/primary-search-bar.jsx
>      if (this.props.onSearch && this.props.isValid !== false) {
We should probably test this change and make sure it doesn't affect default behavior of search bar on other pages.

2021-03-02 16:53 UTC, kscoulter approved these changes
Looks good

2021-03-03 14:13 UTC, kscoulter requested changes

2021-03-03 14:13 UTC, kscoulter commented on test/jest/client/components/organisms/primary-search-bar/primary-search-bar.test.js
> +  it('does not run the search when the search button is clicked but the for field is invalid', () => {
typo `for` instead of `form`

2021-03-03 14:13 UTC, kscoulter commented on test/jest/client/components/organisms/primary-search-bar/primary-search-bar.test.js
> +    console.log('onSearchMock is', onSearchMock)
remove log

2021-03-03 14:13 UTC, kscoulter commented on test/jest/client/components/organisms/primary-search-bar/primary-search-bar.test.js
> +    console.log('onSearchMock is', onSearchMock)
remove

2021-03-03 14:21 UTC, peggles2 commented on test/jest/client/components/organisms/primary-search-bar/primary-search-bar.test.js
> +    console.log('onSearchMock is', onSearchMock)
helps if I push my changes before review lol

2021-03-03 14:21 UTC, peggles2 commented on test/jest/client/components/organisms/primary-search-bar/primary-search-bar.test.js
> +    console.log('onSearchMock is', onSearchMock)
helps if I push my changes before review lol

2021-03-03 14:25 UTC, kscoulter approved these changes

2021-03-03 14:30 UTC, merged