TC-817 - Styling for district office in results list
USSBA/sba-gov-katana pull request #1206
Opened 2021-04-06 14:59 UTC by peggles2

This pull request styles the district office so it stands out from the rest of the result list. 
![Screen Shot 2021-04-06 at 10 56 37 AM](https://user-images.githubusercontent.com/7727136/113731659-f4390280-96c6-11eb-8047-db633d41805f.png)

2021-04-06 15:19 UTC, kscoulter requested changes

2021-04-06 15:19 UTC, kscoulter commented on src/client/components/organisms/office-result/office-result.scss
> +  border: 2px solid #007dbc;
Can you use CSS variables for colors?

2021-04-06 15:19 UTC, kscoulter commented on src/client/components/organisms/office-result/office-result.scss
> +  box-shadow: 1px 1px 4px 4px #4e8dbe;
Use a variable for color

2021-04-06 15:19 UTC, kscoulter commented on src/client/components/organisms/office-result/office-result.scss
> +}
Why do you need both `.districtOffice` and `.pullLeft`? They do the same thing.

Floating can have unintended consequences, are you user that's the only solution here?

2021-04-06 15:19 UTC, kscoulter commented on src/client/components/organisms/office-result/office-result.jsx
> +                    {console.log('distance', distance)}
remove console log

2021-04-06 15:19 UTC, kscoulter commented on src/client/components/organisms/office-result/office-result.jsx
> +                      ''
maybe use null instead of empty string?

2021-04-06 15:22 UTC, peggles2 commented on src/client/components/organisms/office-result/office-result.jsx
> +                    {console.log('distance', distance)}
ooo good catch

2021-04-06 15:22 UTC, peggles2 commented on src/client/components/organisms/office-result/office-result.scss
> +}
Yes otherwise the div will fall on next line.

2021-04-06 19:37 UTC, kscoulter approved these changes

2021-04-07 15:30 UTC, kscoulter commented on src/client/components/organisms/office-result/office-result.jsx
> +                      <div className={styles.districtOfficeText}>Your District Office - </div>
Why not wrap the div around the distance to prevent separation? `<div> Your District Office - <Distance /> </div>` ?

2021-04-07 15:38 UTC, peggles2 commented on src/client/components/organisms/office-result/office-result.jsx
> +                      <div className={styles.districtOfficeText}>Your District Office - </div>
It's simpler this way. Distance has a bunch of conditions on its own.

2021-04-07 16:09 UTC, kscoulter approved these changes

2021-04-07 16:42 UTC, merged