Feature/district office drag map
USSBA/sba-gov-katana pull request #1209
Opened 2021-04-12 20:12 UTC by peggles2

This pull request allows for the district office to be displayed while the map is being dragged.

2021-04-12 20:59 UTC, kscoulter requested changes

2021-04-12 20:59 UTC, kscoulter commented on src/client/components/templates/search/search.jsx
> +  getDistrictOffice(searchParams, searchType, output, zip) {
rename output variable - it is very unclear what it's supposed to be

2021-04-12 20:59 UTC, kscoulter commented on src/client/components/templates/search/search.jsx
> +            if (searchParams.address || searchParams.mapCenter) {
why is this if needed?

2021-04-12 20:59 UTC, kscoulter commented on src/client/components/templates/search/search.jsx
> +                  this.getDistrictOffice(searchParams, searchType, output, zip)
Do we need a search type variable here at all? It will always be "offices" right?

2021-04-12 20:59 UTC, kscoulter commented on src/client/components/templates/search/search.jsx
> +              if (searchParams.mapCenter && !searchParams.address) {
Will this execute on find a lender too? Do we need to prevent this behavior on other pages?

2021-04-13 13:58 UTC, peggles2 commented on src/client/components/templates/search/search.jsx
> +            if (searchParams.address || searchParams.mapCenter) {
Its needed to make sure that this only occurs for office lookup and not the other search pages.

2021-04-13 13:58 UTC, peggles2 commented on src/client/components/templates/search/search.jsx
> +              if (searchParams.mapCenter && !searchParams.address) {
No because of that if condition.

2021-04-13 16:09 UTC, peggles2 commented on src/client/components/templates/search/search.jsx
> +                  this.getDistrictOffice(searchParams, searchType, output, zip)
Yes its needed for the api call. But the searchParam is not so I took that out

2021-04-14 13:19 UTC, mikewolfd approved these changes

2021-04-14 13:24 UTC, merged