TC-739 info button
USSBA/sba-gov-katana pull request #1210
Opened 2021-04-19 19:12 UTC by kscoulter

Add info button to primary search bar. Toggle text on click.

![Screen Shot 2021-04-19 at 3 12 14 PM](https://user-images.githubusercontent.com/12025195/115290545-ae962400-a121-11eb-8556-1e06482d25ab.png)

![Screen Shot 2021-04-19 at 3 12 08 PM](https://user-images.githubusercontent.com/12025195/115290547-af2eba80-a121-11eb-8c2b-4a721414c091.png)

![Screen Shot 2021-04-19 at 3 12 00 PM](https://user-images.githubusercontent.com/12025195/115290548-af2eba80-a121-11eb-98e6-07aec41b5f38.png)

2021-04-19 19:49 UTC, peggles2 commented on src/client/components/atoms/button/button.scss
> +  color: $sba-white;
nice job adding a variable

2021-04-19 19:56 UTC, peggles2 requested changes
Looks good just a few comments.

2021-04-19 19:56 UTC, peggles2 commented on src/client/components/organisms/primary-search-bar/primary-search-bar.scss
> -
nice job cleaning up some code.

2021-04-19 19:56 UTC, peggles2 commented on test/jest/client/components/organisms/primary-search-bar/primary-search-bar.test.js
> +
Can you also write a test of what the expected behavior should be during initial page load? So the info text does not display initially.

2021-04-19 20:06 UTC, kscoulter commented on src/client/components/atoms/button/button.scss
> +
Not sure what you mean by this.

2021-04-19 20:09 UTC, peggles2 commented on src/client/components/atoms/button/button.scss
> +
placing it in variables.scss

2021-04-20 13:46 UTC, kscoulter commented on src/client/components/atoms/button/button.scss
> +
secondary blue is already a variable

2021-04-20 13:51 UTC, peggles2 approved these changes
LGTM 👍

2021-04-21 13:42 UTC, peggles2 approved these changes
LGTM 👍

2021-04-21 16:42 UTC, merged