Feature/zip removed
USSBA/sba-gov-katana pull request #1230
Opened 2021-06-03 16:23 UTC by peggles2

This pull request populates the zip code search field with the new zip location when the map is dragged.

2021-06-03 16:43 UTC, kscoulter requested changes
You should probably add the zip to prop types in office map component.

2021-06-03 16:43 UTC, kscoulter commented on src/client/components/organisms/office-map/office-map.jsx
> +    const { onFieldChange, selectedItem, newCenter, onDragEnd, hoveredMarkerId, total, zip } = this.props
you don't need to destructure zip here, doesn't seem like you're using that variable anymore

2021-06-03 16:43 UTC, kscoulter commented on src/client/components/organisms/office-map/office-map.jsx
> +    if (zip !== this.props.zip) {
what happens on other pages that use office map but don't pass the zip?

2021-06-04 20:21 UTC, kscoulter commented on src/client/components/organisms/office-map/office-map.jsx
> +    if (zip !== this.props.zip) {
@peggles2, did you see this question?

2021-06-04 20:49 UTC, peggles2 commented on src/client/components/organisms/office-map/office-map.jsx
> +    if (zip !== this.props.zip) {
only other office page is find a lender and if you look at the code you see I updated it to handle that.

2021-06-07 13:58 UTC, kscoulter approved these changes

2021-06-07 18:31 UTC, merged